config/routes.rb
Lunarquest::Application.routes.draw do
  resources :words do 
    get 'translate', :on => :collection
  end
  resources :languages

  root to: 'words#translate'

end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :description, :name
  has_many  :words, inverse_of: :language
  # has_many  :translations, foreign_key: 
  # has_many  :translations, foreign_key: 
  validates :name, uniqueness: {case_sensitive: false},
                   presence: true
  validates :description, length: { maximum: 150 }
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def index
    @languages = Language.all
  end

  def show
    @language = Language.find(params[:id])
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.new(params[:language])
    if @language.save
      redirect_to @language, :notice => "Successfully created language."
    else
      render :action => 'new'
    end
  end

  def edit
    @language = Language.find(params[:id])
  end

  def update
    @language = Language.find(params[:id])
    if @language.update_attributes(params[:language])
      redirect_to @language, :notice  => "Successfully updated language."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @language = Language.find(params[:id])
    @language.destroy
    redirect_to languages_url, :notice => "Successfully destroyed language."
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_for @language do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/languages/edit.html.erb
<% title "Edit Language" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @language %> |
  <%= link_to "View All", languages_path %>
</p>

app/views/languages/index.html.erb
<% title "Languages" %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% for language in @languages %>
    <tr>
      <td><%= language.name %></td>
      <td><%= language.description %></td>
      <td><%= link_to "Show", language %></td>
      <td><%= link_to "Edit", edit_language_path(language) %></td>
      <td><%= link_to "Destroy", language, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Language", new_language_path %></p>

app/views/languages/new.html.erb
<% title "New Language" %>

<%= render 'form' %>

<p><%= link_to "Back to List", languages_path %></p>

app/views/languages/show.html.erb
<% title "Language" %>

<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @language.description %>
</p>

<p>
  <%= link_to "Edit", edit_language_path(@language) %> |
  <%= link_to "Destroy", @language, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", languages_path %>
</p>