config/routes.rb
Lunarquest::Application.routes.draw do
  resources :words do 
    get 'translate', :on => :collection
  end
  resources :languages

  root to: 'words#translate'

end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessor :double_error
  attr_accessible :details, :value, :language_id, :translations_attributes
  belongs_to  :language, inverse_of: :words

  has_many :translations, autosave: true, inverse_of: :word, dependent: :destroy
  has_many :direct_meanings, through: :translations, source: :translated_word

  has_many :reverse_translations, foreign_key: "translated_word_id", class_name: "Translation", dependent: :destroy, autosave: true
  has_many :inferred_meanings, through: :reverse_translations, source: :word 

  accepts_nested_attributes_for :translations, allow_destroy: true, 
                                reject_if: :t_word_blank?
  before_validation :b_check_for_double_errors, only: :value
  before_validation :a_check_if_translated_word_exists, only: :translations

  validates   :value, presence: true,
                      uniqueness: { case_sensitive: false, scope: :language_id}
  validates   :language, presence: true
 
  scope :in_language, lambda { |*args| {conditions: ["language_id = ?", (args.first.id || 1)]} }

  def meanings_in(language)
    direct = self.direct_meanings.where("translated_language_id = ?", language.id) 
    inferred = self.inferred_meanings.where("original_language_id = ?", language.id) 
    direct + inferred
  end

  def add_meaning_in(language,translated_word_value)
    # TO-DO: Assuming for now that language is an existing Language object    
    trans_word = Word.find_or_create_by_value_and_language_id(translated_word_value,language.id)
    unless Translation.translation_exists?(self, self.language, trans_word, trans_word.language)
      t = self.translations.build(translated_word: trans_word)
      t.save
    end   
  end

  def self.find_or_create_by_value_and_language_id(word_value, language_id, &block)
    obj = self.find_by_value_and_language_id(word_value, language_id) || Language.find(language_id).words.create(value: word_value)
  end

  def self.word_exists?(word_value,language)
    Word.where("value = ? AND language_id = ?", word_value, language.id).exists?
  end  

  def self.search(query)
    if query
      find(:all, conditions: ['value @@ :q', q: query])
    else
      find(:all)
    end
  end

  def a_check_if_translated_word_exists
    wrong_translations, good_translations = [], []
    self.translations.each do |translation|
      # first check if there are two identical [words,langs] in currently analyzed form
      if (wrong_translations+good_translations).map(&:translated_word).
        map { |tw| [tw.value,tw.language] }.include?([translation.translated_word.value, translation.translated_word.language])
        # set the double error virtual attr for translation 
        # (it will be proxied to translated_word in translation before_validation filter)
        translation.double_t_word_error = :same_form
        wrong_translations << translation
        next
      end
      if w = Word.find_by_value_and_language_id(translation.translated_word.value,translation.translated_word.language_id)
        # if Translation.find_by_translated_word_id_and_translated_language_id(w.id, w.language_id)
        if  Translation.translation_exists?(self, self.language, w, w.language)  
          translation.double_t_word_error = :same_language
          wrong_translations << translation
        else
          # discard current translation and create another one on the fly  
          add_meaning_in(w.language,w.value)
        end
      else
        good_translations << translation        
      end
    end
    self.translations = wrong_translations + good_translations
  end

  def b_check_for_double_errors
    message = case @double_error
      when :same_form
      "This translation is already on the list"
      when :same_language
      "This translation is already added to dictionary (maybe inferred)"
    end
    errors.add(:value, message) if @double_error 
  end

  def t_word_blank?(attributes)
    if attributes['translated_word_attributes']
      attributes['translated_word_attributes']['value'].blank?
    else
      false
    end
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @languages = Language.all
    @words = if params[:query]
       Word.search(params[:query])     
    else
       Word.all
    end
  end

  def translate
    @languages = Language.all
    lang_from  = Language.find params[:language_from] unless params[:language_from].blank? 
    lang_to    = Language.find params[:language_to] unless params[:language_to].blank?
    unless params[:query].blank? || params[:language_from].blank? || params[:language_to].blank?
      @words = Word.in_language(lang_from).search(params[:query])
      @translations = []
      @words.each do |w|
        w.meanings_in(lang_to).each { |m| @translations << m.value }
      end
    end
  end

  def show
    @word = Word.find(params[:id])
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(params[:word])
    if @word.save
      redirect_to @word, :notice => "Successfully created word."
    else
      render :action => 'new'
    end
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])
    if @word.update_attributes(params[:word])
      redirect_to @word, :notice  => "Successfully updated word."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to words_url, :notice => "Successfully destroyed word."
  end

end

app/helpers/words_helper.rb
module WordsHelper
  def link_to_add_translation_row(name, f, association) 
    new_object = f.object.send(association).klass.new
    new_object.build_translated_word
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render 'translation_fields', f: builder
    end
    link_to(name, '#', id: "add_transl_btn", class: "btn btn-success add_transl_btn", data: {id: id, fields: fields.gsub("\n", "")})   
  end

  def setup(word)    
    unless word.errors.any?
      word.translations.build.build_translated_word
    end
    word
  end

  def word_field_starting_value(params)    
    params[:word] ? params[:word][:value] : params[:w]
  end
end

app/views/words/_form.html.erb
<%= simple_form_for setup(@word), html: { class: 'form-horizontal' } do |w_builder| %>

  <% if @word.errors.any? %>
    <%= render 'word_errors' %>
  <% end %>

  <fieldset>
    <legend><%= controller.action_name.capitalize %> Word</legend>
    <% unless params[:action]=='edit' %>    
      <%= w_builder.input :value, label: "Word", input_html: { value: word_field_starting_value(params) } %>
    <% else %>
      <%= w_builder.input :value, label: "Word" %>
    <% end %>
    <%= w_builder.association :language, prompt: "Select language"%>
    <legend>Add/Edit translations</legend>
    <%= w_builder.simple_fields_for :translations do |t_builder| %>
      <%= render 'translation_fields', f: t_builder %>
    <% end -%>  
    <div class="form-actions">      
      <%= link_to_add_translation_row("+ Add meaning", w_builder, :translations) if action=='edit' %>
      <%= w_builder.submit nil, :class => 'btn btn-primary', id: 'create_or_update_word_btn' %>
      <%= link_to 'Cancel', words_path, :class => 'btn' %>
    </div>
  </fieldset>

<% end %>

app/views/words/_translation_fields.html.erb
<div class="translation_fields">
<%= f.simple_fields_for :translated_word, html: { class: 'form-inline' } do |builder| %>
  <%= builder.input :value, label: "Word", wrapper_html: {class: "pull-left" } %>
  <div class="control-group select required word_language">
    <div class="controls">
      <%= builder.select :language_id, options_from_collection_for_select(Language.all, "id", "name", builder.object.language_id), prompt: "Select language"%>
      <%= f.hidden_field :_destroy, value: "" %><%= link_to raw('<i class="icon-trash"></i>'), '#', class: "remove_word_btn"  %>
    </div>    
  </div>
<% end -%>
</div>

app/views/words/_word_errors.html.erb
<div id="error_explanation">
  <h2><%= pluralize(@word.errors.count, "error") %> prohibited this offer from being saved:</h2>

  <ul>
  <% @word.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>

app/views/words/edit.html.erb
<%= render 'form', action: 'edit' %>

<p>
  <%= link_to "Show", @word %> |
  <%= link_to "View All", words_path %>
</p>

app/views/words/index.html.erb
<% title "Words", false %>
<%= form_tag words_path, class: "form-search", method: 'get' do %>
<legend>Search for words</legend>
  <%= content_tag :div, class: "input-append" do %>
    <%= search_field_tag :query, params[:query], class: "span3 search-query" %>
    <%# select_tag :language, options_from_collection_for_select(@languages, "id", "name"), prompt: "Select language" %>
    <%= submit_tag "Search", name: nil, class: "btn btn-info" %>
  <% end -%>
<% end %>

<% unless @words.empty? %>
  <table class="table table-striped table-bordered">
    <tr>
      <th>#</th>
      <th>Word</th>
      <th>Language</th>
      <th>Actions</th>
    </tr>
    <% @words.each_with_index do |word,i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= link_to word.value, word_path(word) %></td>
        <td><%= word.language.name %></td>
        <td>
        <%= link_to "Edit", edit_word_path(word), class: 'btn btn-mini btn-info' %>
        <%= link_to "Destroy", word, :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </table>
<% end -%>

<%= form_tag new_word_path, class: "form-search", method: 'get' do %>
<legend>Create new word</legend>
  <%= content_tag :div, class: "input-append" do %>
    <%= search_field_tag :w, params[:w], class: "span3 search-query" %>
    <%= submit_tag "+ New Word", name: nil, class: "btn btn-success" %>
  <% end -%>
<% end %>

app/views/words/new.html.erb
<%= render 'form', action: 'edit' %>

<p><%= link_to "Back to List", words_path %></p>

app/views/words/show.html.erb
<% title "Word" %>

<p>
  <strong>Value:</strong>
  <%= @word.value %>
</p>
<p>
  <strong>Details:</strong>
  <%= @word.details %>
</p>
<p>
  <strong>Language:</strong>
  <%= @word.language_id %>
</p>

<p>
  <%= link_to "Edit", edit_word_path(@word) %> |
  <%= link_to "Destroy", @word, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", words_path %>
</p>

app/views/words/translate.html.erb
<% title "Translate", false %>
<%= form_tag translate_words_path, class: "form-search", method: 'get' do %>
  <legend>Translate baby!</legend>
    <%= label_tag "From:" %>
    <%= select_tag :language_from, 
                 options_from_collection_for_select(@languages, "id", "name", params[:language_from]), 
                 prompt: "Select language:" %>
    <%= content_tag :div, class: "input-append" do %>
      <%= search_field_tag :query, params[:query], class: "search-query", placeholder: 'Type in word' %>
      <%= submit_tag "Translate", name: nil, class: "btn btn-success" %>
    <% end -%>
    <%= label_tag "To:" %>
    <%= select_tag :language_to, 
                  options_from_collection_for_select(@languages, "id", "name", params[:language_to]), 
                  prompt: "Select language:" %>
  
<% end %>

<% unless params[:query].blank? || params[:language_from].blank? || params[:language_to].blank? %>
  <% unless @translations.empty? %>
    <h3>Translations in <%= Language.find(params[:language_to]).name %> for "<%= params[:query] %>":</h3>
    <div>
      <ul>
        <% @translations.each do |t| %>
          <li><%= t %>
        <% end -%>
      </ul> 
    </div>
  <% else -%>
    <p>Sorry, no translations found :(</p>
  <% end -%>
<% end -%>